name: Build Gists Project

on: [pull_request_target]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Navigate to app directory
        run: cd ./app

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build
        continue-on-error: true

      - name: Check build status
        run: exit $?
        if: ${{ failure() }}

      - name: Prevent merging if build fails
        run: echo "Build failed, preventing merge." && exit 1
        if: ${{ failure() }}
